import { QuestionIdEnum } from '../enums/QuestionIdEnum';
import type { AnswerConfigEntry } from '../interfaces/AnswerConfigEntry';

/** Question-matching rules; first matching entry wins. Order entries by specificity. */
export const ANSWERS_CONFIG: AnswerConfigEntry[] = [
  // ── Identity (high priority, specific first) ──────────────────────────
  {
    patterns: ['first name', 'given name', 'forename', /^first$/],
    threshold: 55,
    questionId: QuestionIdEnum.FirstName,
  },
  {
    patterns: ['last name', 'surname', 'family name', /^last$/],
    threshold: 55,
    questionId: QuestionIdEnum.LastName,
  },
  {
    patterns: ['legal name', 'full name', 'name as per'],
    threshold: 45,
    questionId: QuestionIdEnum.FullName,
  },
  {
    patterns: ['preferred name', 'nickname', 'name you go by'],
    threshold: 40,
    questionId: QuestionIdEnum.PreferredName,
  },

  // ── Contact ───────────────────────────────────────────────────────────
  {
    patterns: ['email', 'e-mail', 'email address', 'work email'],
    threshold: 55,
    questionId: QuestionIdEnum.Email,
  },
  {
    patterns: ['device type', 'mobile type', 'phone type', 'contact type'],
    threshold: 50,
    questionId: QuestionIdEnum.DeviceType,
  },
  {
    patterns: [
      'preferred contact',
      'contact method',
      'how should we contact',
      'best way to reach',
    ],
    threshold: 35,
    questionId: QuestionIdEnum.PreferredContact,
  },
  {
    patterns: [
      'phone number',
      'phone no',
      'mobile number',
      'cell number',
      'contact number',
      'telephone',
      'whatsapp',
      'alternate phone',
      'secondary phone',
      /phone\s*number/,
      /^phone$/,
      /^mobile$/,
    ],
    threshold: 50,
    questionId: QuestionIdEnum.Phone,
  },

  // ── Employment (current) ──────────────────────────────────────────────
  {
    patterns: [
      'current job title',
      'present job title',
      'current designation',
      'present designation',
      'current role',
    ],
    threshold: 45,
    questionId: QuestionIdEnum.CurrentJobTitle,
  },
  {
    patterns: [
      'current company',
      'present company',
      'current employer',
      'present employer',
      'company you work',
    ],
    threshold: 30,
    questionId: QuestionIdEnum.CurrentCompany,
  },
  {
    patterns: [
      'current location',
      'current city',
      'present location',
      'where are you located',
      'city you are based',
    ],
    threshold: 30,
    questionId: QuestionIdEnum.CurrentLocation,
  },
  {
    patterns: [
      'years of experience',
      'total experience',
      'overall experience',
      'years of relevant experience',
      /experience.*year/,
      /years.*experience/,
    ],
    threshold: 45,
    questionId: QuestionIdEnum.YearsOfExperience,
  },

  // ── Compensation & availability ─────────────────────────────────────
  {
    patterns: [
      'current salary',
      'current ctc',
      'present salary',
      'present ctc',
      'current compensation',
      /current.*(salary|ctc|compensation)/,
    ],
    threshold: 45,
    subPatterns: [
      {
        patterns: ['lpa', 'lakhs', 'lakh'],
        threshold: 10,
        questionId: QuestionIdEnum.CurrentCtcLpa,
      },
    ],
    questionId: QuestionIdEnum.CurrentCtc,
  },
  {
    patterns: [
      'expected salary',
      'expected ctc',
      'desired salary',
      'desired ctc',
      'salary expectation',
      'compensation expectation',
      /expected.*(salary|ctc|compensation)/,
    ],
    threshold: 45,
    subPatterns: [
      {
        patterns: ['lpa', 'lakhs', 'lakh'],
        threshold: 10,
        questionId: QuestionIdEnum.ExpectedCtcLpa,
      },
    ],
    questionId: QuestionIdEnum.ExpectedCtc,
  },
  {
    patterns: [
      'competing offer ctc',
      'competing offer salary',
      'other offer ctc',
      'other offer salary',
      'competing compensation',
      'other offer compensation',
      'offer ctc',
      'offer salary',
      'competing offer',
      'other offer',
      'another offer',
      'counter offer',
      'offer in hand',
      'holding offer',
      'existing offer',
      'multiple offers',
      'other job offer',
      'parallel offer',
      'offer from another',
      'do you have an offer',
      'any other offer',
      'offer elsewhere',
      /competing.*(ctc|salary|compensation|offer)/,
      /other.*offer/,
    ],
    threshold: 40,
    subPatterns: [
      {
        patterns: ['lpa', 'lakhs', 'lakh'],
        threshold: 10,
        questionId: QuestionIdEnum.CompetingOfferLpa,
      },
    ],
    questionId: QuestionIdEnum.CompetingOfferCtc,
  },
  {
    patterns: [
      'notice period negotiable',
      'notice negotiable',
      'negotiable notice',
      'negotiable notice period',
      'is your notice negotiable',
      'is notice negotiable',
      'can you negotiate notice',
      'can notice be negotiated',
      'notice period flexible',
      'flexible notice period',
      'willing to negotiate notice',
      'negotiate your notice',
      'negotiate notice period',
      'notice negotiation',
      'shorten notice period',
      'reduce notice period',
      'early release from notice',
      'join before notice ends',
      'join earlier than notice',
      'early joining possible',
      /notice.*negotiable/,
      /negotiable.*notice/,
    ],
    threshold: 10,
    questionId: QuestionIdEnum.NoticePeriodNegotiable,
  },
  {
    patterns: ['salary negotiable', 'open to negotiation', 'ctc negotiable', 'compensation negotiable'],
    threshold: 30,
    questionId: QuestionIdEnum.SalaryNegotiable,
  },
  {
    patterns: [
      'notice period',
      'serving notice',
      'notice in days',
      /notice.*period/,
    ],
    threshold: 45,
    questionId: QuestionIdEnum.NoticePeriod,
  },
  {
    patterns: [
      'when can you join',
      'joining time',
      'earliest start',
      'available to start',
      'start date',
      'date available',
    ],
    threshold: 35,
    questionId: QuestionIdEnum.JoiningTime,
  },

  // ── Links & portfolio ─────────────────────────────────────────────────
  {
    patterns: ['linkedin', 'linkedin profile', 'linkedin url', 'linkedin link'],
    threshold: 60,
    questionId: QuestionIdEnum.LinkedIn,
  },
  {
    patterns: ['github', 'github profile', 'github url', 'github link'],
    threshold: 60,
    questionId: QuestionIdEnum.GitHub,
  },
  {
    patterns: [
      'portfolio',
      'personal website',
      'website url',
      'portfolio url',
      'personal site',
      /portfolio|website/,
    ],
    threshold: 45,
    questionId: QuestionIdEnum.Portfolio,
  },
  {
    patterns: ['leetcode', 'hackerrank', 'codility', 'codechef', 'codeforces'],
    threshold: 55,
    questionId: QuestionIdEnum.LeetCode,
  },

  // ── Location & address ────────────────────────────────────────────────
  {
    patterns: ['country of residence', 'country you live', 'residence country'],
    threshold: 35,
    questionId: QuestionIdEnum.CountryOfResidence,
  },
  {
    patterns: ['country', 'nation', 'which country'],
    threshold: 50,
    questionId: QuestionIdEnum.Country,
  },
  {
    patterns: ['nationality', 'citizenship', 'citizen of'],
    threshold: 35,
    questionId: QuestionIdEnum.Nationality,
  },
  {
    patterns: ['city', 'town', 'municipality'],
    threshold: 50,
    questionId: QuestionIdEnum.City,
  },
  {
    patterns: ['state', 'province', 'region', 'county'],
    threshold: 50,
    questionId: QuestionIdEnum.State,
  },
  {
    patterns: [
      'address line 1',
      'street address',
      'address 1',
      'house number',
      'flat no',
      'apartment',
    ],
    threshold: 45,
    questionId: QuestionIdEnum.AddressLine1,
  },
  {
    patterns: ['address line 2', 'address 2', 'landmark', 'area', 'locality'],
    threshold: 45,
    questionId: QuestionIdEnum.AddressLine2,
  },
  {
    patterns: [
      'pin code',
      'pincode',
      'postal code',
      'zip code',
      'zip',
      'postcode',
    ],
    threshold: 50,
    questionId: QuestionIdEnum.PinCode,
  },
  {
    patterns: [
      'full address',
      'current address',
      'permanent address',
      'mailing address',
    ],
    threshold: 40,
    questionId: QuestionIdEnum.FullAddress,
  },

  // ── Work preferences ──────────────────────────────────────────────────
  {
    patterns: [
      'willing to relocate',
      'open to relocation',
      'relocate',
      'relocation',
    ],
    threshold: 25,
    questionId: QuestionIdEnum.WillingToRelocate,
  },
  {
    patterns: [
      'employment type',
      'job type',
      'full time',
      'part time',
      'contract',
    ],
    threshold: 40,
    questionId: QuestionIdEnum.EmploymentType,
  },
  {
    patterns: ['willing to travel', 'travel required', 'business travel'],
    threshold: 25,
    questionId: QuestionIdEnum.WillingToTravel,
  },
  {
    patterns: ['shift', 'night shift', 'rotational shift', 'work shift'],
    threshold: 40,
    questionId: QuestionIdEnum.WorkShift,
  },

  // ── Work authorization & compliance ───────────────────────────────────
  {
    patterns: [
      'legally authorized',
      'authorized to work',
      'work authorization',
      'work eligibility',
      'eligible to work',
      'right to work',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.LegallyAuthorizedToWork,
  },
  {
    patterns: [
      'visa sponsorship',
      'require sponsorship',
      'need sponsorship',
      'immigration sponsorship',
      'work visa',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.VisaSponsorshipRequired,
  },
  {
    patterns: ['work permit', 'permit expiry', 'visa expiry', 'visa status'],
    threshold: 5,
    questionId: QuestionIdEnum.VisaStatus,
  },
  {
    patterns: [
      'conflict of interest',
      'financial interest',
      'outside business interest',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.ConflictOfInterest,
  },
  {
    patterns: [
      'relative working',
      'family member employed',
      'know anyone at',
      'employee referral relation',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.RelativeAtCompany,
  },
  {
    patterns: [
      'non-compete',
      'non compete',
      'restrictive covenant',
      'bound by agreement',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.NonCompeteAgreement,
  },
  {
    patterns: [
      'background check',
      'criminal record',
      'felony',
      'convicted',
      'criminal history',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.CriminalRecord,
  },
  {
    patterns: ['security clearance', 'government clearance'],
    threshold: 5,
    questionId: QuestionIdEnum.SecurityClearance,
  },
  {
    patterns: [
      'terms and conditions',
      'privacy policy',
      'consent',
      'agree to',
      'i confirm',
      'i certify',
      'declaration',
      'accuracy of information',
    ],
    threshold: 5,
    questionId: QuestionIdEnum.TermsConsent,
  },

  // ── EEO / voluntary disclosure ────────────────────────────────────────
  {
    patterns: ['gender', 'sex'],
    threshold: 40,
    questionId: QuestionIdEnum.Gender,
  },
  {
    patterns: ['pronouns', 'preferred pronouns'],
    threshold: 35,
    questionId: QuestionIdEnum.Pronouns,
  },
  {
    patterns: ['date of birth', 'dob', 'birth date', 'birthday'],
    threshold: 50,
    questionId: QuestionIdEnum.DateOfBirth,
  },
  {
    patterns: ['ethnicity', 'race', 'racial background'],
    threshold: 15,
    questionId: QuestionIdEnum.Ethnicity,
  },
  {
    patterns: ['veteran', 'military service', 'armed forces'],
    threshold: 15,
    questionId: QuestionIdEnum.VeteranStatus,
  },
  {
    patterns: ['disability', 'disabled', 'accommodation'],
    threshold: 15,
    questionId: QuestionIdEnum.DisabilityStatus,
  },
  {
    patterns: ['lgbtq', 'sexual orientation'],
    threshold: 15,
    questionId: QuestionIdEnum.SexualOrientation,
  },
  {
    patterns: ['marital status', 'marriage status'],
    threshold: 40,
    questionId: QuestionIdEnum.MaritalStatus,
  },

  // ── Education ─────────────────────────────────────────────────────────
  {
    patterns: [
      'highest degree',
      'highest education',
      'education level',
      'qualification',
    ],
    threshold: 45,
    questionId: QuestionIdEnum.HighestDegree,
  },
  {
    patterns: ['university', 'college', 'institution', 'school name'],
    threshold: 45,
    questionId: QuestionIdEnum.University,
  },
  {
    patterns: [
      'field of study',
      'major',
      'specialization',
      'discipline',
      'degree in',
    ],
    threshold: 45,
    questionId: QuestionIdEnum.FieldOfStudy,
  },
  {
    patterns: [
      'graduation year',
      'year of graduation',
      'passing year',
      'year completed',
    ],
    threshold: 45,
    questionId: QuestionIdEnum.GraduationYear,
  },
  {
    patterns: ['gpa', 'cgpa', 'grade point'],
    threshold: 50,
    questionId: QuestionIdEnum.Gpa,
  },

  // ── Skills & languages ──────────────────────────────────────────────────
  {
    patterns: ['certification', 'certifications', 'professional certification'],
    threshold: 40,
    questionId: QuestionIdEnum.Certification,
  },

  // ── Application meta ──────────────────────────────────────────────────
  {
    patterns: [
      'reason for leaving',
      'why leaving',
      'leaving your current job',
      'leaving current job',
      'why are you leaving',
      'why job switch',
      'job switch',
      'looking for a change',
      'why change job',
      'why are you switching',
      'why are you looking for',
      'looking for a new job',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.ReasonForLeaving,
  },
  {
    patterns: [
      'why should we hire',
      'why hire you',
      'asset to this organisation',
      'asset to this organization',
      'asset to the organisation',
      'asset to the organization',
      'different from other candidates',
      'makes you different',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.WhyHireYou,
  },
  {
    patterns: [
      'why are you interested',
      'interested in this job',
      'interested in this role',
      'why do you want to work',
      'want to work at our',
      'want to work at your',
      'why do you want to join',
      'want to join us',
      'want to join our',
      'why this company',
      'why our company',
      'why do you want',
      'why this role',
      'why join',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.WhyApply,
  },
  {
    patterns: [
      'conflict with a teammate',
      'conflict with teammate',
      'conflict with a colleague',
      'conflict with colleague',
      'disagree with your approach',
      "don't agree with your approach",
      'do not agree with your approach',
      'people disagree',
      'how did you resolve',
      'resolve the conflict',
      'handle disagreement',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.ConflictResolution,
  },
  {
    patterns: [
      'achievement you are proud',
      'achievement proud',
      'proud of',
      'biggest impact',
      'impact on users',
      'impact on business',
      'feature you built',
      'project you built',
      'specific contribution',
      'challenging technical problem',
      'technical problem you solved',
      'how did you approach it',
      'difficult problem',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.Achievement,
  },
  {
    patterns: [
      'next 5 years',
      'next five years',
      'see yourself in',
      'where do you see yourself',
      'career goals',
      'goals and aspirations',
      'aspirations in life',
      'what you want to do',
      'want to do in life',
      'long term goals',
      'future goals',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.FiveYearGoals,
  },
  {
    patterns: [
      'how did you hear',
      'where did you hear',
      'referral source',
      'source of application',
      'how did you find',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.ReferralSource,
  },
  {
    patterns: [
      'current employee',
      'worked here before',
      'previous employee',
      'rehire',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.PreviousEmployee,
  },
  {
    patterns: [
      'bond',
      'employment bond',
      'service bond',
      'training bond',
      'retention bond',
      'bond period',
      'under bond',
      'serving bond',
      'notice buyout',
      'buy out notice',
      'buyout notice',
      'notice buy out',
      'buy out your notice',
      'notice period buyout',
      'pay notice buyout',
    ],
    threshold: 10,
    questionId: QuestionIdEnum.NoticeBuyoutBond,
  },
];
